blog/urls.py
from django.urls import path, include

from .feeds import LatestEntriesFeed
from .views import PostDetailView, TagListView, CategoryListView, PostIndexView, PostYearView, PostMonthView, PostDayView, SearchResultsView, MediaDetailView


urlpatterns = [
    path('', PostIndexView.as_view()),
    path('feed/', LatestEntriesFeed()),
    path('results/', SearchResultsView.as_view(), name='blog_search_list'),
    path('media/<name>/', MediaDetailView.as_view()),
    path('page/<int:page>/', PostIndexView.as_view()),
    path('category/<slug:slug>/', CategoryListView.as_view()),
    path('category/<slug:slug>/page/<int:page>/', CategoryListView.as_view()),
    path('tag/<slug:slug>/', TagListView.as_view()),
    path('tag/<slug:slug>/page/<int:page>/', TagListView.as_view()),
    path('<int:year>/', PostYearView.as_view()),
    path('<int:year>/page/<int:page>/', PostYearView.as_view()),
    path('<int:year>/<int:month>/', PostMonthView.as_view()),
    path('<int:year>/<int:month>/page/<int:page>/', PostMonthView.as_view()),
    path('<int:year>/<int:month>/<int:day>/', PostDayView.as_view()),
    path('<int:year>/<int:month>/<int:day>/page/<int:page>/', PostDayView.as_view()),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>/', PostDetailView.as_view()),
]

comments/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.contrib.sites.models import Site
from django.contrib.flatpages.models import FlatPage

import hashlib
import uuid
import logging
from mptt.models import MPTTModel, TreeForeignKey
from precise_bbcode.bbcode import get_parser
from akismet import Akismet

from blog.models import Post

logger = logging.getLogger(__name__)


class Commenter(models.Model):
    username = models.CharField(max_length=200)
    email = models.EmailField()
    website = models.URLField(blank=True)
    approved = models.BooleanField(default=False)
    spam = models.BooleanField(default=False)
    
    def approve(self):
        self.approved = True
        for comment in Comment.objects.filter(author=self):
            comment.approve()
        self.save()
    
    def unapprove(self):
        self.approved = False
        for comment in Comment.objects.filter(author=self):
            comment.unapprove()
        self.save()
        
    def mark_spam(self):
        self.spam = True
        for comment in Comment.objects.filter(author=self):
            comment.spam = True
            comment.save()
        self.save()
        
    def mark_safe(self):
        self.spam = False
        for comment in Comment.objects.filter(author=self):
            comment.spam = False
            comment.save()
        self.save()
    
    def get_commenter_text(self):
        if self.website:
            return '<a href="%s">%s</a>' % (self.website, self.username)
        return self.username
    
    def get_profile_url(self):
        email_hash = hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()
        return "https://www.gravatar.com/%s" % (email_hash)
    
    def get_image_url(self):
        email_hash = hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()
        return "https://www.gravatar.com/avatar/%s?s=%s" % (email_hash, str(50))
    
    def __str__(self):
        return self.username


class Comment(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children', db_index=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True, blank=True, related_name='comments')
    page_url = models.CharField(max_length=100, blank=True)
    approved = models.BooleanField(default=False, db_index=True)
    pub_date = models.DateTimeField('date published', default=timezone.now, editable=False, db_index=True)
    author = models.ForeignKey(Commenter, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField(blank=True) # form should force this field anyway, so this is just for the admin
    notify = models.BooleanField(default=False)
    spam = models.BooleanField(default=False)
    html_text = models.TextField(blank=True) # creating this field to take wordpress imported comments because they're formatted in html
    uuid = models.UUIDField(default=uuid.uuid4, editable=False)
    
    class Meta:
        ordering = ['pub_date']
        
    class MPTTMeta:
        order_insertion_by = ['pub_date']
        
    def __str__(self):
        return str(self.pk)
    
    def get_absolute_url(self):
        if self.post:
            base_url = self.post.get_absolute_url()
        else:
            base_url = self.page_url
        return base_url + '#comment' + str(self.uuid)
        
    def get_unsubscribe_url(self):
        if self.post:
            base_url = self.post.get_absolute_url()
        else:
            base_url = self.page_url
        unsubscribe_query = '?email=%s&comment=%s' % (self.author.email, str(self.uuid))
        return base_url + unsubscribe_query
    
    def approve(self):
        self.approved = True
        self.save()
    
    def unapprove(self):
        self.approved = False
        self.save()
        
    def get_post_title(self):
        if self.post:
            return self.post.title
        # if post isn't set, it's a page, so try to find it
        try:
            page = FlatPage.objects.get(url=self.page_url)
            return page.title
        except(FlatPage.DoesNotExist, FlatPage.MultipleObjectsReturned):
            logger.error('FlatPage query error: %s' % self.page_url)
            
    def save(self, *args, **kwargs): # override save to parse bbcode first
        if self.text:
            parser = get_parser()
            self.html_text = parser.render(self.text)
        super().save(*args, **kwargs)
    
    # if the email passed in matches the author, then turn off notifications
    def unsubscribe(self, email):
        if email == self.author.email:
            self.notify = False
            self.save()
    
    def send_email_notification(self, info_dict, recipients):
        if self.author.email in recipients: # don't send comments to yourself
            recipients.remove(self.author.email)
        if len(recipients) < 1: # if there are no more recipients, quit out
            return
        subject = "New comment on %s" % self.get_post_title()
        comment_url = info_dict['url']
        context = { 'comment_author': self.author.username,
                    'comment_text': self.text,
                    'comment_url': comment_url,
                    'unsubscribe_url': info_dict['unsubscribe']
        }
        body = "Check out the reply to your comment at %s" % comment_url
        html_body = render_to_string('comments/comment_body.html', context)
        msg = EmailMultiAlternatives(subject=subject, from_email="marth@mail.marthaurion.com",
                                    to=recipients, body=body)
        msg.attach_alternative(html_body, "text/html")
        msg.send()
        
    def notify_authors(self):
        if not self.notify:
            return []
        recipients = [self.author.email] # first send the notification to the parent comment's author
        return recipients
    
    def send_notifications(self, info_dict):
        if self.spam_check(info_dict): # don't send notifications for suspected spam
            return
        self.send_email_notification(info_dict, ["marthaurion@gmail.com"]) # first always send notification to me, the admin
        if self.parent and self.approved:
            self.send_email_notification(info_dict, self.parent.notify_authors())
            
    def spam_check(self, info_dict):
        if self.author.spam:
            return True
        
        approved = self.author.approved
        if approved:
            return False
        current_domain = Site.objects.get_current().domain
        user_agent = 'Marth Blog/0.0.1'
        akismet = Akismet(settings.AKISMET_KEY, 'http://{0}'.format(current_domain), user_agent)
        is_spam = akismet.check(info_dict['remote_addr'],
                                info_dict['user_agent'],
                                comment_author=self.author.username,
                                comment_author_email=self.author.email,
                                comment_author_url=self.author.website,
                                comment_content=self.text)
        if is_spam:
            self.author.mark_spam()
        return is_spam
        
    def get_request_info(self, request):
        info_dict = {}
        info_dict['url'] = request.build_absolute_uri(self.get_absolute_url())
        info_dict['unsubscribe'] = request.build_absolute_uri(self.get_unsubscribe_url())
        info_dict['remote_addr'] = request.META.get('REMOTE_ADDR')
        info_dict['user_agent'] = request.META.get('HTTP_USER_AGENT')
        return info_dict

comments/forms.py
from django import forms


class CommentForm(forms.Form):
    username = forms.CharField(max_length=200, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    website = forms.URLField(required=False, widget=forms.URLInput(attrs={'class': 'form-control'}))
    text = forms.CharField(required=True, widget=forms.Textarea(attrs={'class': 'form-control', 'id': 'comment-form-text'}))
    parent = forms.CharField(required=False, widget=forms.HiddenInput(attrs={'id': 'comment-form-parent'}))

comments/views.py
from django.utils import timezone
from django.conf import settings

import logging
import datetime

from .models import Comment, Commenter
from .forms import CommentForm
from .tasks import send_email

logger = logging.getLogger(__name__)


class CommentFormMixin(object):
    form_class = CommentForm
    
    # override initial values for the form to use session values for a commenter if they exist
    def get_initial(self):
        return { 'username': self.request.session.get('comment_username'),
                'email': self.request.session.get('comment_email'),
                'website': self.request.session.get('comment_website') }

    def comment_check(self, request, form, post=None, page_url=''):
        form_email = form.cleaned_data['email']
        form_username = form.cleaned_data['username']
        form_website = form.cleaned_data['website']
        try:
            author = Commenter.objects.get(email=form_email)
            changed = False
            # if username or website are changed, update them for the author of the comment
            if form_website and form_website != author.website:
                author.website = form_website
                changed = True
            if form_username and form_username != author.username:
                author.username = form_username
                changed = True
            if changed:
                author.save()
        except Commenter.DoesNotExist: # if no commenter is found for the email in the form, create one
            author = Commenter()
            author.email = form_email
            author.username = form_username
            author.website = form_website
            author.save()
        except Commenter.MultipleObjectsReturned: # probably shouldn't happen, but here just in case
            logger.error('Multiple commenters found for email: %s' % form_email)
            return self.form_invalid(form)
        
        request.session['comment_email'] = author.email  # save commenter information in a session so it can be reused later
        request.session['comment_username'] = author.username
        request.session['comment_website'] = author.website
        
        # prep comment fields before creating the new comment
        parent = None
        if form.cleaned_data['parent']:
            parent_id = form.cleaned_data['parent'].replace('#comment','')
            try:
                parent = Comment.objects.get(uuid=parent_id)
            except (Comment.MultipleObjectsReturned, Comment.DoesNotExist):
                logger.error('Invalid parent comment id: %d' % parent_id)
        comment_notify = bool(request.POST.get('notify', False))
        
        search_time = timezone.now()-datetime.timedelta(seconds=10)
        # try to find the same comment in the last 10 seconds or create a new one otherwise
        comment, created = Comment.objects.get_or_create(
            parent=parent,
            post=post, # this will be None if it's a page
            page_url=page_url, # this will be an empty string if it's a post
            pub_date__gt=search_time,
            text=form.cleaned_data['text'],
            author=author,
            approved=author.approved,
            notify=comment_notify,
            spam=author.spam
        )
        self.success_url = comment.get_absolute_url()
        if not created: # if this is a duplicate, return without notification
            return self.form_valid(form)
        
        request.session['comment_notify'] = comment_notify # log notification setting in the session
        
        request_info = comment.get_request_info(request)
        if settings.DEV_SERVER: # can't set up celery on cloud9, so running the standard email
            comment.send_notifications(request_info)
        else:
            send_email.delay(comment.pk, request_info)
        return self.form_valid(form)
        
    def unsubscribe_comment(self, uuid, email):
        try:
            comment = Comment.objects.get(uuid=uuid)
            comment.unsubscribe(email)
        except (Comment.MultipleObjectsReturned, Comment.DoesNotExist):
            logger.error('Email unsubscribe failed for comment: %d' % uuid)

templates/comments/_post_comments.html
{% if comment_list %}
    {% load mptt_tags %}
    <ul class="list-unstyled" id="comment-list">
    {% recursetree comment_list %}
        {% if not node.is_child_node %}
            <li class="media" id="comment{{ node.uuid }}">
        {% else %}
            <div class="media" id="comment{{ node.uuid }}">
        {% endif %}
            <div class="media-left mr-3">
                <a href="{{ node.author.get_profile_url }}">
                    <img class="media-object" src="{{ node.author.get_image_url }}" alt="testing" height="50" width="50" />
                </a>
            </div>
            <div class="media-body">
                <h4 class="media-heading">
                    {% if node.author.website %}
                        <a href="{{ node.author.website }}">{{ node.author.username }}</a>
                    {% else %}
                        {{ node.author.username }}
                    {% endif %}
                </h4>
                <a href="{{ node.get_absolute_url }}"><small class="text-muted">{{ node.pub_date }}</small></a>
                <p>{{ node.html_text|safe }}</p>
                <p><a href="#comment{{ node.uuid }}" onclick="replyForm(this, '{{ node.uuid }}')">Reply</a></p>
            {% if not node.is_leaf_node and node.level < 2 %}
                {{ children }}
                </div>
            {% else %}
                </div>
            {% endif %}
        {% if not node.is_child_node %}
            </li>
        {% elif not node.is_leaf_node and node.level >= 2 %}
            </div>
            {{ children }}
        {% else %}
            </div>
        {% endif %}
    {% endrecursetree %}
    </ul>
{% else %}
    <h4>No comments found.</h4>
    <br>
{% endif %}

<div class="card" id="comment-form">
    <div class="card-body">
        <h4><strong>Leave a comment</strong></h4>
        <p id='cancel-reply' hidden><a href="#comment-form" onclick="cancelReply()">Cancel Reply to Comment</a></p>
        {% if comment_username %}
            <p id="comment_collapse"><strong>Commenting as</strong>: {{ comment_username }} <a href="#comment_form" onclick="handleChangeClick()">Change</a></p>
        {% endif %}
        <form action="{{ post_comment_url }}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div id="comment_group_name" class="form-group"{{ comment_hidden }}>
                {{ form.username.errors }}
                <label for="{{ form.username.id_for_label }}">Name:</label>
                {{ form.username }}
            </div>
            <div id="comment_group_email" class="form-group"{{ comment_hidden }}>
                {{ form.email.errors }}
                <label for="{{ form.email.id_for_label }}">Email:</label>
                {{ form.email }}
            </div>
            <div id="comment_group_website" class="form-group"{{ comment_hidden }}>
                {{ form.website.errors }}
                <label for="{{ form.website.id_for_label }}">Website:</label>
                {{ form.website }}
            </div>
            <div class="form-group">
                {{ form.text.errors }}
                <div><label for="{{ form.text.id_for_label }}">Comment:</label></div>
                <p class="pull-right">
                    <a href="javascript:void(insertBBCode('b'))" class="btn btn-primary btn-xs" role="button">b</a>
                    <a href="javascript:void(insertBBCode('i'))" class="btn btn-primary btn-xs" role="button">i</a>
                    <a href="javascript:void(insertBBCode('u'))" class="btn btn-primary btn-xs" role="button">u</a>
                    <a href="javascript:void(insertBBCode('quote'))" class="btn btn-primary btn-xs" role="button">quote</a>
                </p>
                {{ form.text }}
            </div>
            <div class="form-group">{{ form.parent }}</div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="notify" {% if comment_notify %}checked{% endif %} />Notify me with replies</label>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Post Comment" />
            </div>
        </form>
    </div>
</div>

templates/comments/comment_body.html
<html>
    <p>New comment made by {{ comment_author }}</p>
    <p>{{ comment_text|escape|urlize|linebreaksbr }}</p>
    <p>Check out the comment <a href="{{ comment_url }}">here</a>.</p>
    <hr>
    <p><a href="{{ unsubscribe_url }}">Click here to unsubscribe from replies to this comment.</a></p>
</html>